In [3]:
import warnings
warnings.filterwarnings('ignore')
from sklearn import preprocessing
from sklearn import datasets as d
import numpy as np

In [9]:
iris = d.load_iris()
iris_x = iris.data

In [10]:
impute = preprocessing.Imputer()
iris_x_prime = impute.fit_transform(iris_x)
iris_x_prime[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

缺失值可以有四种方式填充：  
* 均值mean（默认方法）  
* 中位数median  
* 众数most_frequent  
* 指定值
上面的的imputer函数使用了均值来填充缺失值，下面用中位数来填充

In [11]:
impute = preprocessing.Imputer(strategy='median')
iris_x_prime = impute.fit_transform(iris_x)
iris_x_prime[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

指定填充值

In [12]:
impute = preprocessing.Imputer(missing_values=-1)
iris_x_prime = impute.fit_transform(iris_x)
iris_x_prime[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

pandas的$fillna()$方法也可以处理缺失值，而且更加灵活，$fillna()$可以填充任意统计参数值，但是重用性较弱

In [21]:
import pandas as pd
iris_df = pd.DataFrame(iris_x)
iris_df.fillna(iris_df.max()).head(3)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2